name: CI

on:
  push:
    branches: [main, update_flake_lock_action]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_conf: |
            extra-substituters = https://cache.nixos.asia/oss
            extra-trusted-public-keys = oss:KO872wNJkCDgmGN3xy9dT89WAhvv13EiKncTtHDItVU=
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: nix profile install github:juspay/vira --accept-flake-config
      - name: Configure Attic cache
        run: nix shell nixpkgs#attic-client -c attic login cache-nixos-asia https://cache.nixos.asia "$ATTIC_TOKEN"
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
      - run: vira ci
        env:
          GH_TOKEN: ${{ github.token }}
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
