name: CI

on:
  pull_request:
  push:
    branches: [main, mvp1-v2]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Check flake
        run: nix flake check --accept-flake-config

      - name: Build package
        run: nix build . --no-link --print-out-paths --accept-flake-config > store-path

      - name: Attic login
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/mvp1-v2'
        run: nix run nixpkgs#attic-client -- login chutney https://cache.nixos.asia ${{ secrets.ATTIC_LOGIN_TOKEN }}

      - name: Push to attic
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/mvp1-v2'
        run: nix run nixpkgs#attic-client -- push chutney:oss $(cat store-path)
